### PR TITLE
Add specs

### PR DESCRIPTION
**Pull request by joel**

### CODE REVIEW

**Comment by nragaz** [comment]
I'm happy for you to maintain a fork using RSpec, but that's not the testing framework I want to use.

**Comment by joel** [comment]
It's my first changes, i want to add some feature, but this it's preliminary for me.

**Comment by joel** [comment]
I will make a new one PR, maybe this could interest you

**Comment by joel** [comment]
Otherwise I will keep this fork in / / do not worry.

**Pull request closed without merging**
